version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
  fluentbit:
    image: fluent/fluent-bit:1.8
    volumes:
      - ./fluent-bit.conf:/conf/fluent-bit.conf:ro
      - ./parsers.conf:/conf/parsers.conf:ro
      - ./sample.log:/logs/sample.log:ro
    command:
      - /fluent-bit/bin/fluent-bit
      - -c
      - /conf/fluent-bit.conf
